version: "3.8"

services:
  cqf-ruler:
    build: .
    image: cqf-ruler:latest
    container_name: cqf-ruler
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1g
    restart: unless-stopped
    # uncomment to persist logs or config
    # volumes:
    #   - ./data:/app/data
