version: "3.8"

services:
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-documentserver
    restart: unless-stopped
    environment:
      - JWT_ENABLED=false
    ports:
      - "8880:80"
      # - "8443:443"
    # volumes:
    #   - onlyoffice_data:/var/www/onlyoffice/Data
    #   - onlyoffice_log:/var/log/onlyoffice
    #   - onlyoffice_fonts:/usr/share/fonts/truetype/custom
    #   - onlyoffice_forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten
# volumes:
#   onlyoffice_data:
#   onlyoffice_log:
#   onlyoffice_fonts:
#   onlyoffice_forgotten:
