services:
  postgres:
    image: postgres:15
    container_name: postgres_langflow
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    restart: unless-stopped

  langflow:
    image: langflowai/langflow:latest
    container_name: langflow
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - LANGFLOW_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - LANGFLOW_AUTO_LOGIN=true
      - LANGFLOW_SUPERUSER=admin
      - LANGFLOW_SUPERUSER_PASSWORD=admin123
      - LANGFLOW_SECRET_KEY=my-secret-key-langflow
      - LANGFLOW_NEW_USER_IS_ACTIVE=true
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
