version: "3.8"

services:
  cds-at:
    image: hlseven/cds-connect-authoring-tool:latest
    environment:
      MONGO_URL: mongodb://cds-at-mongo/cds_authoring
      CQL_TO_ELM_URL: http://cds-at-cql2elm:8080/cql/translator
      CQL_FORMATTER_URL: http://cds-at-cql2elm:8080/cql/formatter
      NODE_ENV: development
    volumes:
      - ./api/config:/usr/src/app/api/config
    ports:
      - "3001:3001"
      - "9000:9000"
    links:
      - cds-at-mongo
      - cds-at-cql2elm
  cds-at-mongo:
    image: mongo:8
    ports:
      - "27017:27017"
  cds-at-cql2elm:
    image: cqframework/cql-translation-service:v2.6.0
