version: "3.8"

services:
  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db # 📦 lưu dữ liệu MongoDB
    restart: unless-stopped

  cql2elm:
    image: cqframework/cql-translation-service:v2.6.0
    restart: unless-stopped

  app:
    image: hlseven/cds-connect-authoring-tool:latest
    depends_on:
      - mongo
      - cql2elm
    ports:
      - "9000:9000" # port frontend / proxy
      - "3001:3001" # port backend API nếu cần
    environment:
      CQL_TO_ELM_URL: http://cql2elm:8080/cql/translator
      CQL_FORMATTER_URL: http://cql2elm:8080/cql/formatter
      MONGO_URL: mongodb://mongo/cds_authoring
      AUTH_SESSION_SECRET: secretkey123
      NODE_ENV: development
      API_PROXY_ACTIVE: "false"
    restart: unless-stopped

volumes:
  mongo_data:
