version: "3.8"

services:
  libreoffice:
    image: libreoffice/online:master
    container_name: libreoffice-online
    restart: unless-stopped
    environment:
      - domain=localhost
      - username=admin
      - password=admin123
      - DONT_GEN_SSL_CERT=1
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:net.frame_ancestors=* --o:net.service_root=/liboffice
    ports:
      - "9980:9980"
    volumes:
      - libreoffice_data:/opt/lool/systemplate
      - libreoffice_cache:/tmp
      - ./config/coolwsd.xml:/etc/coolwsd/coolwsd.xml:ro
    cap_add:
      - MKNOD

volumes:
  libreoffice_data:
  libreoffice_cache:
